server:
  port: ${PORT:${SERVER_PORT:8080}}


spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - FilterCustom
      routes:
        - id: productRoute #identificador de la ruta
          uri : http://localhost:8082/ #uri del microservicio a donde redirecciono
          predicates:
           - Path=/product/** #ruta del microservicio
        - id: userRoute #identificador de la ruta
          uri : http://localhost:8081/ #uri del microservicio
          predicates:
           - Path=/user/** #ruta del microservicio
          filters:
           - AddRequestHeader=user-request-header, custom-user-request-header #agregar cabecera
           - AddResponseHeader=user-response-header, custom-user-response-header #agregar cabecera

eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      registry-fetch-interval-seconds: 5
      healthcheck:
        enabled: true
      service-url:
          default-zone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 10

management:
    endpoint:
      health:
          enabled: true
          show-details: always
      shutdown:
          enabled: true
    endpoints:
        web:
          exposure:
            include: "*"

